namespace: multi-cluster-traffic-controller-system

resources:
  - ingress.yaml
  - service.yaml

secretGenerator:
- name: ingress-tls
  files:
    - tls/tls.crt
    - tls/tls.key

generatorOptions:
  disableNameSuffixHash: true