apiVersion: v1
kind: Service
metadata:
  name: webhooks
spec:
  ports:
    - name: webhooks
      port: 9090
      targetPort: webhooks
      protocol: TCP
  selector:
    control-plane: controller-manager