apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

helmCharts:
  - name: istiod
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.16.2
    releaseName: mctc
    namespace: istio
    includeCRDs: true
