# Adds namespace to all resources.
namespace: mctc-system
resources:
- role.yaml
- serviceaccount.yaml
- rolebinding.yaml
- syncer.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: syncer
  newName: syncer
  newTag: latest

patches:
- path: syncer_parameter_patch.json
  target:
    group: apps
    kind: Deployment
    name: sync-agent
    version: v1
